name: Create Release
on:
  push:
    branches:
      - master
      
jobs:
  release-linux:
    permissions: write-all
    name: Release (Linux)
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: "./gradlew build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --scan --no-daemon fatJar
      - name: Rename files
        run: cp build/libs/Client-all.jar goldfish-linux.jar
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: linux-latest
          prerelease: true
          title: 'Development Build - Linux'
          files: |
            goldfish-linux.jar
  release-osx:
    permissions: write-all
    name: Release (Mac OSX)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: "./gradlew build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --scan --no-daemon fatJar
      - name: Rename files
        run: cp build/libs/Client-all.jar goldfish-osx.jar
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: osx-latest
          prerelease: true
          title: 'Development Build - Mac OSX'
          files: |
            goldfish-osx.jar
  release-windows:
    permissions: write-all
    name: Release (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: "./gradlew build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --scan --no-daemon fatJar
      - name: Rename files
        run: cp build/libs/Client-all.jar goldfish-windows.jar
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: windows-latest
          prerelease: true
          title: 'Development Build - Windows'
          files: |
            goldfish-windows.jar