name: Create Pre-Release

on:
  push:
    branches:
      - "master"

jobs:
  pre-release-linux:
    permissions: write-all
    
    name: "Pre Release - Linux"

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: fatJar
      - name: Rename files
        run: cp Client/build/libs/Client-all.jar Goldfish.jar
      - uses: "marvinpinto/action-automatic-releases@${{ matrix.os }}"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ matrix.os }}"
          prerelease: true
          title: "Development Build - ${{ matrix.os }}"
          files: |
            Goldfish.jar