name: Create Pre-Release

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    permissions: write-all
    
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build command with Gradle
        run: ./gradlew build
      - name: Build jar with Gradle
        run: ./gradlew fatJar
      - name: Rename files
        run: cp Client/build/libs/Client-all.jar Goldfish.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            Goldfish.jar