name: Create Pre-Release

on:
  push:
    branches:
      - "master"

jobs:
  pre-release-linux:
    permissions: write-all
    
    name: "Pre Release - Linux"

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build command with Gradle
        run: ./gradlew build
      - name: Build jar with Gradle
        run: ./gradlew fatJar
      - name: Rename files
        run: cp Client/build/libs/Client-all.jar Goldfish.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-${{ matrix.os }}"
          prerelease: true
          title: "Development Build - ${{ matrix.os }}"
          files: |
            Goldfish.jar