name: Create Pre-Release
'on':
  push:
    branches:
      - build
jobs:
  pre-release-linux:
    permissions: write-all
    name: Pre Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup and execute Gradle 'farJar' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: farJar
      - name: Rename files
        run: cp build/libs/Client-all.jar Goldfish.jar
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{ matrix.os }}
          prerelease: true
          title: 'Development Build - ${{ matrix.os }}'
          files: |
            Goldfish.jar
